Shopiva/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    re_path('^api/', include(('serverapi.urls', 'serverapi'), namespace='api')),
    re_path(r'^gp/', include(('order.urls', 'order'), namespace='order')),
    path('register/', include(('register.urls', 'register'), namespace='register')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

home/urls.py
# home\urls.py
from django.urls import path, re_path
from home import views

app_name = "home"
urlpatterns = [
    path('', views.home_view, name='productsPage'),
    re_path('^products/', views.product_details_view, name='productDetailsPage'),
re_path('^wishlist/', views.wishlist_view, name='wishlistPage'),
]

order/urls.py
# order\urls.py
from django.urls import path, re_path
from . import views

app_name = "order"
urlpatterns = [
    re_path(r'^profile/$', views.profile_view, name='profilePage'),
    re_path(r'^cart/$', views.cart_view, name='cartPage'),
    re_path(r'^cartToOrderRedirect/$', views.convert_cart_to_order, name='cartToOrderRedirect'),
    re_path('^orderhistory/', views.order_history_view, name='orderHistoryPage'),
    re_path('^yourtransactions/', views.transactions_view, name='transactionsPage'),
    re_path('^yourprofile/', views.profile_view, name='profilePage'),
]

register/urls.py
# register\urls.py
from django.urls import path, re_path
from register import views

app_name = "register"
urlpatterns = [
    path('', views.signup_view, name='loginPage'),
    path('signin/', views.signin_view, name='signinPage'),
    path('logout/', views.logout_view, name='logoutPage'),
]


home/models.py
# home\models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models
from django.contrib.auth.models import User, AbstractUser, PermissionsMixin
from django.db.models import Sum, F, Count, Value, Avg
from django.db.models.functions import Length, Upper
from django.core.validators import MaxValueValidator
import uuid
from order.models import Orders, OrderItem


class CustomerManager(BaseUserManager):
    def create_user(self, userEmail, first_name, last_name,
                    password = None,
                    is_admin = False,
                    is_staff = False,
                    is_active = True):
        if not userEmail:
            raise ValueError("User must have an email")
        if not password:
            raise ValueError("User must have a password")
        if not first_name:
            raise ValueError("User must have a First Name")
        if not last_name:
            raise ValueError("User must have a Last Name")

        user = self.model(userEmail=self.normalize_email(userEmail))
        user.first_name = first_name
        user.last_name = last_name
        user.is_admin = is_admin
        user.is_staff = is_staff
        user.is_active = is_active
        user.set_password(password)
        user.save(using=self._db)

    def create_staffuser(self, userEmail, first_name, last_name,
                         password = None,):
        user = self.create_user(userEmail, first_name, last_name,
                                password, is_staff = True,)
        return user

    def create_superuser(self, userEmail, first_name, last_name,
                         password = None, **kwargs):
        if not userEmail:
            raise ValueError("User must have an email")
        if not password:
            raise ValueError("User must have a password")
        if not first_name:
            raise ValueError("User must have a First Name")
        if not last_name:
            raise ValueError("User must have a Last Name")
        user = self.model(userEmail = self.normalize_email(userEmail))
        user.first_name = first_name
        user.last_name = last_name
        user.is_admin = True
        user.is_staff = True
        user.is_active = True
        user.set_password(password)
        user.save(using=self._db)


class Customers(AbstractBaseUser, PermissionsMixin):
    userID = models.UUIDField(primary_key=True, auto_created=True, default=uuid.uuid4, editable=False, unique=True)
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    userPhone = models.PositiveIntegerField(unique=True, null=True, blank=True)
    userEmail = models.EmailField(unique=True)
    userImage = models.ImageField(blank=True, null=True)
    timeStamp = models.DateTimeField(auto_now_add=True)

    objects = CustomerManager()
    is_active = models.BooleanField(default=True, blank=True)
    is_admin = models.BooleanField(default=False, blank=True)
    is_staff = models.BooleanField(default=False, blank=True)
    USERNAME_FIELD = 'userEmail'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    @property
    def userName(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def get_full_name(self):
        # The user is identified by their email address
        return self.userName

    def get_short_name(self):
        return self.first_name

    def get_user_id(self):
        return self.userID

    @staticmethod
    def has_perm(perm, obj = None ):
        # "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    @staticmethod
    def has_module_perms(app_label):
        # "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    def __str__(self):
        return self.userName

    class Meta:
        verbose_name_plural = "Customers"


class Products(models.Model):
    CATEGORY = (
        ('Wearable', 'Wearable'),
        ('Electronics', 'Electronics'),
        ('Books', 'Books'),
        ('Footwear', 'Footwear'),
        ('Stationary', 'Stationary')
    )
    productID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    productName = models.CharField(max_length=255)
    productPrice = models.DecimalField(max_digits=10, decimal_places=0)
    productCategory = models.CharField(max_length=32, choices= CATEGORY)
    productImage = models.ImageField(upload_to='images/')
    productDescription = models.CharField(max_length=512, null=True)
    timeStamp = models.DateTimeField(auto_now_add=True)

    @property
    def productRating(self):
        return Products.objects.get(productID=self.productID).ratings_set.aggregate(Avg('ratings'))['ratings__avg'] or 0
        # {'ratings__avg':5.0}

    @property
    def productReviews(self):
        return int(Products.objects.get(productID=self.productID).ratings_set.count())
        # 2

    @property
    def productOrders(self):
        return Products.objects.get(productID=self.productID).orderitem_set.all().filter(order__status='Delivered').aggregate(Sum('quantity'))['quantity__sum']

    def __str__(self):
        return ' ProductID: {} | ProductName: {}'.format(str(self.productID), str(self.productName))

    class Meta:
        verbose_name_plural = "Products"


class Wishlist(models.Model):
    """
        Each customer, ie. user may have one or more wishlists to remember items
        for later acquisition.
    """
    customer = models.ForeignKey(Customers, on_delete=models.CASCADE, null=True)
    timeStamp = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    def add_to_cart(self, productID):
        product = Products.objects.get(productID=productID)
        cart, created = Orders.objects.get_or_create(customer=self.customer, status='In Cart')
        cartItem, created = OrderItem.objects.get_or_create(order=cart, product=product)
        cartItem.quantity = 1
        cartItem.save()
        self.delete_item(productID)
        return cart.get_cartitems_quantity

    @property
    def get_wishlist_quantity(self):
        """
        :return: Number of items in wishlist
        """
        return self.wishlistitem_set.all().count()

    def add_item(self, productID):
        """
            Adds the exact product to this wishlist, if it is not already there.
        """
        product = Products.objects.get(productID=productID)
        items = WishlistItem.objects.filter(wishlist=self, product=product)
        if not items.exists():
            item = WishlistItem.objects.create(wishlist=self, product=product)
            item.savedProductPrice = product.productPrice
            item.save()
        self.save()  # to get the last updated timestamp for this wishlist

    def get_all_items(self):
        """
        :returns: all items of this wishlist
        """
        return WishlistItem.objects.filter(wishlist=self)

    def find_item(self, productID):
        """
            For a given product and its variation, find an entry in this wishlist
            and return the found WishlistItem or None.
        """
        product = Products.objects.get(productID=productID)
        return WishlistItem.objects.filter(wishlist=self, product=product)

    def delete_item(self, productID):
        """
            A simple convenience method to delete an item from the wishlist.
        """
        product = Products.objects.get(productID=productID)
        WishlistItem.objects.get(wishlist=self, product=product).delete()
        self.save()

    class Meta(object):
        verbose_name = 'Wishlist'
        verbose_name_plural = 'Wishlists'


class WishlistItem(models.Model):
    """
        This is a holder for the item in the wishlist.
    """
    wishlist = models.ForeignKey(Wishlist, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, null=True)
    savedProductPrice = models.IntegerField(null=True, blank=True)
    # variation = models.JSONField(null=True, blank=True)
    # variation_hash = models.CharField(max_length=64, null=True)

    class Meta(object):
        verbose_name = 'Wishlist item'
        verbose_name_plural = 'Wishlist items'


class Ratings(models.Model):
    customer = models.ForeignKey(Customers, on_delete=models.SET_NULL, null=True)
    productID = models.ForeignKey(Products, on_delete=models.CASCADE, null=True)
    ratings = models.PositiveIntegerField(validators=[MaxValueValidator(5)], null=True, blank=True, default=0)
    subject = models.CharField(max_length=63, blank=True, null=True)
    comment = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_created=True, auto_now=True)

    def __str__(self):
        return 'Product ID: {} | Rating : {}'.format(str(self.productID), str(self.ratings))

    class Meta:
        verbose_name_plural = "Ratings"


class Attributes(models.Model):
    productID = models.OneToOneField(Products, primary_key=True, default=uuid.uuid4(), on_delete=models.CASCADE)
    bulletin1 = models.CharField(null=True, blank=True, max_length=64)
    bulletin2 = models.CharField(null=True, blank=True, max_length=64)
    bulletin3 = models.CharField(null=True, blank=True, max_length=64)
    bulletin4 = models.CharField(null=True, blank=True, max_length=64)
    bulletin5 = models.CharField(null=True, blank=True, max_length=64)

    def __str__(self):
        return str(self.productID)

    class Meta:
        verbose_name_plural = "Attributes"

home/forms.py
from django.forms import ModelForm
from django import forms
from home.models import Ratings


class ReviewForm(ModelForm):
    subject = forms.CharField(label='', max_length=255,
                              widget=forms.TextInput(attrs={'class': 'form-control',
                                                            'placeholder': "What's most important to know"}))
    comment = forms.CharField(label='', max_length=2048,
                              widget=forms.Textarea(attrs={'class': 'form-control',
                                                           'placeholder': 'What did you Like or dislike? What did you '
                                                                          'use this product for?',
                                                           'max_length': 2048}))

    class Meta:
        model = Ratings
        fields = ('subject', 'comment', 'ratings')

home/views.py
# home/urls.py
import base64

from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from home.forms import ReviewForm
from order.models import Orders, OrderItem
from home.models import Customers, Products, Ratings, Wishlist


def home_view(request):
    if request.user.is_authenticated:
        customer = request.user
        cart, created = Orders.objects.get_or_create(customer=customer, status='In Cart')
        wishlist, created = Wishlist.objects.get_or_create(customer=customer)
    else:
        cart = {'get_cartitems_quantity': 0, 'get_cart_total': 0}
        wishlist = {'get_wishlist_quantity': 0}
    products = Products.objects.all()
    attributes = [product.attributes_set.all().first() for product in products]
    prdAndAttr = zip(products, attributes)

    context = {'products': prdAndAttr, 'cart': cart, 'wishlist': wishlist}
    return render(request, 'home/home.html', context)


def product_details_view(request, *args, **kwargs):
    # TODO: USE related_items to concatenate queries
    # TODO: send reviews using AJAX (load more,etc.)
    product_id = request.GET.get("product_id")
    review_form = ReviewForm()
    if request.user.is_authenticated:
        customer = request.user
        cart, created = Orders.objects.get_or_create(customer=customer, status='In Cart')
        wishlist, created = Wishlist.objects.get_or_create(customer=customer)
        try:
            item = cart.orderitem_set.get(product=product_id)
        except OrderItem.DoesNotExist:
            item = []
    else:
        item = []
        cart = {'get_cartitems_quantity': 0, 'get_cart_total': 0}
        wishlist = {'get_wishlist_quantity': 0}

    print('>>>productName:', product_id)
    product = Products.objects.get(productID=product_id)
    attributes = product.attributes_set.all().first()
    try:
        ratings = Ratings.objects.filter(productID=product_id)
    except Ratings.DoesNotExist:
        ratings = []

    '''
        To handle the form submission
    '''
    if request.method == 'POST':
        if request.user.is_authenticated:
            review_form = ReviewForm(data=request.POST)
            if review_form.is_valid():
                review = Ratings()
                review.productID = product
                review.customer = request.user
                review.subject = review_form.cleaned_data['subject']
                review.comment = review_form.cleaned_data['comment']
                if review_form.cleaned_data['ratings'] is not None:
                    review.ratings = review_form.cleaned_data['ratings']
                else:
                    review.ratings = 0
                review.save()
                return JsonResponse({'form_saved': True})
            else:
                return JsonResponse({'form_saved': False})
    return render(request, 'home/product_details.html', {'product': product,
                                                         'attributes': attributes,
                                                         'cart': cart,
                                                         'item': item,
                                                         'ratings': ratings,
                                                         'wishlist': wishlist,
                                                         'review_form': review_form})


def wishlist_view(request):
    if request.user.is_authenticated:
        customer = request.user
        cart, created = Orders.objects.get_or_create(customer=customer, status='In Cart')
        wishlist, created = Wishlist.objects.get_or_create(customer=customer)
    else:
        cart = {'get_cartitems_quantity': 0, 'get_cart_total': 0}
        wishlist = {'get_wishlist_quantity': 0}
    context = {'wishlist':wishlist, 'cart':cart}
    return render(request, 'home/wishlist.html', context)

home/templates/home/card.html
{% load static %}
{% load humanize %}
<div class="container mt-5 productcontainer">
    <section class="section-content padding-y bg" style="background-color: #fafafa">
        <div class="container">
            <div class="row">
                <aside class="col-md-3">
                    <main class="col"></main>
                </aside>
                <main class="col-md-8 mb-5" style="background-color: #f8f9fa; border-radius: 5px">
                            <h4 class="card-title mt-3">Products for You</h4>
                            {% for product,attributes in products %}
                                <div class="col card-body pb-0 pt-0">
                                    <div class="row">
                                        <article class="card card-product-list" id="homecard">
                                            <div class="card-body">
                                                <div class="row">
                                                    <aside class="col-sm-3">
                                                        <a href="#" class="img-wrap">
                                                            <span class="badge badge-danger"> NEW </span>
                                                            <img src="{{ product.productImage.url }}">
                                                        </a>
                                                    </aside>
                                                    <aside class="col-sm-6 pr-0">
                                                        <a href="{% url 'home:productDetailsPage' %}?product_id={{ product.productID }}" class="title mt-2 h5">{{ product.productName }}</a>
                                                        <div class="rating-wrap mb-3">
                                                            <ul class="rating-stars">
                                                                <span class="fa checked fa-star{% if product.productRating < 1 %}-o empty {% endif %}"></span>
                                                                <span class="fa checked fa-star{% if product.productRating < 2 %}-o empty {% endif %}"></span>
                                                                <span class="fa checked fa-star{% if product.productRating < 3 %}-o empty {% endif %}"></span>
                                                                <span class="fa checked fa-star{% if product.productRating < 4 %}-o empty {% endif %}"></span>
                                                                <span class="fa checked fa-star{% if product.productRating < 5 %}-o empty {% endif %}"></span>
                                                            </ul>
                                                            <small class="label-rating text-muted">{{ product.productReviews }} Reviews</small>
                                                            <small class="label-rating text-success">
                                                                 <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bag-check-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                                      <path fill-rule="evenodd" d="M5.5 3.5a2.5 2.5 0 0 1 5 0V4h-5v-.5zm6 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0zm-.646 5.354a.5.5 0 0 0-.708-.708L7.5 10.793 6.354 9.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
                                                                    </svg> {% if product.productOrders %}{{ product.productOrders }}{% else %}0{% endif %} orders
                                                            </small>
                                                        </div>
                                                        <ul>
                                                            <li>{{ attributes.bulletin1 }}</li>
                                                            <li>{{ attributes.bulletin2 }}</li>
                                                            <li>{{ attributes.bulletin3 }}</li>
                                                            <li>{{ attributes.bulletin4 }}</li>
                                                            <li>{{ attributes.bulletin5 }}</li>
                                                        </ul>
                                                    </aside>
                                                    <aside class="col-sm-3">
                                                        <div class="info-aside pr-0">
                                                            <div class="price-wrap mt-2">
                                                                <span class="price h5"> &#x20B9 {{ product.productPrice | intcomma }}</span>
                                                                <del class="price-old"> &#x20B9 980</del>
                                                            </div>
                                                            <p class="small text-success">Free Shipping</p>
                                                            <br>
                                                            <p>
                                                                <button type="button" class="btn btn-primary btn-block update-cart" data-action="add" data-product="{{ product.productID }}">
                                                                    <span class="text">Add to cart <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart3" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                                                                      <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                                                                                                    </svg></span>
                                                                </button>
                                                                <button type="button" class="btn btn-light btn-block border mt-2 update-wishlist" data-action="add" data-product="{{ product.productID }}">
                                                                    <span class="text"> Add to Wishlist</span>
                                                                </button>
                                                            </p>
                                                        </div>
                                                    </aside>
                                                </div>
                                            </div>
                                        </article>
                                    </div>
                                </div>
                            {% endfor %}
                        </main>
            </div>
        </div>
    </section>
</div>

home/templates/home/home.html
{% extends 'home/homemain.html' %}
{% load static %}

{% block content %}
    {% include 'home/navbar.html' %}
    {% include 'home/carousal.html' %}
    {% include 'home/card.html' %}
{% endblock %}

{% block js %}
    <script src="{% static 'js/homecart.js' %}" type="text/javascript"></script>
{% endblock %}

home/templates/home/navbar.html
{% load static %}
<header class="main-header" id="navbar">
    <div class="container">
      <nav class="navbar navbar-expand-lg main-nav px-0">
        <a class="navbar-brand" href="{% url 'home:productsPage' %}">
					      <img src="{% static 'images/logo.png' %}" alt="Shopiva">
					    </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar icon-bar-1"></span>
                        <span class="icon-bar icon-bar-2"></span>
                        <span class="icon-bar icon-bar-3"></span>
                    </button>
        <div class="collapse navbar-collapse" id="mainMenu">
          <ul class="navbar-nav ml-auto text-uppercase f1">
            <li>
              <a href="{% url 'home:productsPage' %}" class="active active-first">home</a>
            </li>
            <li>
              <a href="#about" class="text-nowrap">about us</a>
            </li>
            <li>
              <a href="#service">services</a>
            </li>
            <li>
              <a href="{% url 'home:wishlistPage' %}" id="wishlist" class="text-nowrap">Wishlist
                  {% if wishlist.get_wishlist_quantity %}
                      <span class="badge badge-danger" style="vertical-align: top;"><h7>{{ wishlist.get_wishlist_quantity }}</h7></span>
                  {% endif %}
              </a>
            </li>
            <li>
              <a href="{% url 'order:cartPage' %}" id="cart" class="text-nowrap" >Cart
                  {% if cart.get_cartitems_quantity %}
                      <span class="badge badge-danger" style="vertical-align: top;"><h7>{{ cart.get_cartitems_quantity }}</h7></span>
                  {% endif %}
              </a>
            </li>
            <li>
                {% if request.user.is_authenticated %}<a href='{% url 'order:profilePage' %}' class="text-nowrap">Welcome {{ request.user.first_name }}</a>{% else %}<a href="{% url 'register:loginPage' %}">Login/SignUp</a>{% endif %}
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <!-- /.container -->
</header>

home/templates/home/reviews.html
{% load humanize %}
{% load static %}
{% load crispy_forms_field %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<div class="container-fluid mt-4" style="width: 90%">
    <div class="row">
        <!-- Ratings section -->
        <div class="col-md-6">
            <header class="section-heading">
                <h3><Reviews>Reviews & Ratings</Reviews></h3>
                <div class="rating-wrap">
                    <strong class="label-rating text-lg"> {% if product.productRating %}{{ product.productRating }}{% else %}0{% endif %} <span class="text-muted">| {{ product.productReviews }} Reviews </span></strong>
                </div>
            </header>
            {% for rating in ratings %}
                <article class="box mb-3">
                <div class="icontext w-100">
                    <img src="{% if rating.customer.userImage %}{{ rating.customer.userImage.url }}{% else %}{% static 'images/profile.jpg' %}{% endif %}" class="img-xs icon rounded-circle">
                    <div class="text">
                        <span class="date text-muted float-md-right">{{ rating.updated_at | naturalday:'d M Y, D' | capfirst}} </span>
                        <h6 class="mb-1">{{ rating.customer.userName }}</h6>
                        <ul class="rating-stars">
                            <span class="fa checked fa-star{% if rating.ratings < 1 %}-o empty {% endif %}"></span>
                            <span class="fa checked fa-star{% if rating.ratings < 2 %}-o empty {% endif %}"></span>
                            <span class="fa checked fa-star{% if rating.ratings < 3 %}-o empty {% endif %}"></span>
                            <span class="fa checked fa-star{% if rating.ratings < 4 %}-o empty {% endif %}"></span>
                            <span class="fa checked fa-star{% if rating.ratings < 5 %}-o empty {% endif %}"></span>
                            {% if rating.subject %}<label class="card-title font-weight-bold ml-2">{{ rating.subject }}</label>{% endif %}
                        </ul>

                    </div>
                </div> <!-- icontext.// -->
                {% if rating.comment %}
                <div class="mt-3">
                    <p>
                        {{ rating.comment }}
                    </p>
                </div>
                {% endif %}
            </article>
            {% endfor %}
        </div>
        <!-- Ratings section ended -->

        <!-- Review form section -->
        <div class="col-md-6">
            <header class="section-heading">
                <h3><Reviews>Review the product</Reviews></h3>
                <article class="box">
                    <form method="POST" action="{% url 'home:productDetailsPage' %}?product_id={{ product.productID }}">
                        {% csrf_token %}
                        <label class="font-weight-bold">Add a headline</label>
                        {{ review_form.subject | as_crispy_field }}
                        <label class="font-weight-bold">Add a written review</label>
                        {{ review_form.comment | as_crispy_field }}
                        <div class="form-group">
                            <label class="font-weight-bold">Rating: </label>
                            <div class="input-rating">
                                <span class="rating">
                                    <input type="radio" id="star5" name="ratings" value="5"/><label for="star5"></label>
                                    <input type="radio" id="star4" name="ratings" value="4"/><label for="star4"></label>
                                    <input type="radio" id="star3" name="ratings" value="3"/><label for="star3"></label>
                                    <input type="radio" id="star2" name="ratings" value="2"/><label for="star2"></label>
                                    <input type="radio" id="star1" name="ratings" value="1"/><label for="star1"></label>
                                </span>
                            </div>
                        </div>
                        <button type="submit" value="submit" class="btn {% if request.user.is_authenticated %}btn-primary{% else %}btn-secondary{% endif %}" {% if not request.user.is_authenticated %}disabled{% endif %}>Submit</button>
                    </form>
                    {% if not request.user.is_authenticated %}<p class="text-danger">You must login/signup to review</p>{% endif %}
                </article>

        </div>
        <!-- Review form section ended -->
    </div>
</div>