Shopiva/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    re_path('^api/', include(('serverapi.urls', 'serverapi'), namespace='api')),
    re_path(r'^gp/', include(('order.urls', 'order'), namespace='order')),
    path('register/', include(('register.urls', 'register'), namespace='register')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

home/urls.py
# home\urls.py
from django.urls import path, re_path
from home import views

app_name = "home"
urlpatterns = [
    path('', views.home_view, name='productsPage'),
    re_path('^products/', views.product_details_view, name='productDetailsPage'),
re_path('^wishlist/', views.wishlist_view, name='wishlistPage'),
]

register/urls.py
# register\urls.py
from django.urls import path, re_path
from register import views

app_name = "register"
urlpatterns = [
    path('', views.signup_view, name='loginPage'),
    path('signin/', views.signin_view, name='signinPage'),
    path('logout/', views.logout_view, name='logoutPage'),
]


register/models.py
from django.db import models

# Create your models here.

register/forms.py
from django import forms
from home.models import Customers
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomerCreationForm(UserCreationForm):
    userEmail = forms.CharField(label='', max_length=255,
                                widget=forms.EmailInput(attrs={'class': 'form-control',
                                                               'placeholder': 'johndoe@email.com'}))
    first_name = forms.CharField(label='', max_length=255,
                                 widget=forms.TextInput(attrs={'class': 'form-control',
                                                               'placeholder': 'John'}))
    last_name = forms.CharField(label='', max_length=255,
                                widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'placeholder': 'Doe'}))
    userPhone = forms.IntegerField(label='',
                                   widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                   'placeholder': '1234567809'}))
    password1 = forms.CharField(label='', strip=False,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': '****'}))
    # help_text=password_validation.password_validators_help_text_html(),)
    password2 = forms.CharField(label='', strip=False,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': '****'}))

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('userEmail', 'first_name', 'last_name', 'userPhone')


class CustomerChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = UserChangeForm.Meta.fields

register/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.template import RequestContext

from home.models import Customers
from django.contrib.auth import login, authenticate, logout
from .forms import CustomerCreationForm


# class SignUpView(CreateView):
#    model = Customers
#    form_class = CreateCustomerForm
#    success_url = pass
#    template_name = pass

def signup_view(request):
    # TODO: USE FORM VALIDATION ERROR TAKING EG. FROM OXOTUBE
    signup_form = CustomerCreationForm()
    if request.method == 'POST':
            signup_form = CustomerCreationForm(data=request.POST)
            if signup_form.is_valid():
                print('form valid')
                signup_form.save()
                '''
                    If successfully created account let the user sign in
                '''
                signup_form = CustomerCreationForm()
                context = {'signup_form': signup_form, 'requires_signin': True}
                return render(request, 'register/login.html', context)
            else:
                print('invalid form')
                return redirect('register:loginPage')
    context = {'signup_form': signup_form, 'requires_signin': False}
    return render(request, 'register/login.html', context)


def signin_view(request):
    if request.method == 'POST':
        print("inside sign in")
        userEmail = request.POST['userEmail']
        password = request.POST['password']
        user = authenticate(request, userEmail = userEmail, password = password)
        if user is not None:
            login(request, user)
            return redirect('home:productsPage')
        else:
            return HttpResponse("Invalid Password or Email Address", request)


def logout_view(request):
    logout(request)
    return redirect('home:productsPage')

register/templates/register/login.html
{% extends 'register/loginmain.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="row" xmlns="http://www.w3.org/1999/html">
        <div class="col-md-6 mt-5 ml-8">
            <div class="card shadow-lg">
                <article class="list-group" id="collapselist">
                    <article class="list-group-item">
                                <header class="filter-header">
                                    <a href="" data-toggle="collapse"  data-target="#collapse1" aria-expanded="false" class="collapsed" >
                                        <i class="icon-control fa fa-chevron-down"></i>
                                        <h3 class="title">Sign Up</h3>
                                    </a>
                                </header>
                                <div class="filter-content collapse" data-parent="#collapselist"  id="collapse1">
                                    <form class="block-register" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group form-row">
                                            <label class="col md-3 col-form-label">I am a</label>
                                            <div class="col-sm-9 pt-1">
                                                <label class="custom-control custom-radio custom-control-inline">
                                                    <input class="custom-control-input" checked="" type="radio" name="account_type" value="Buyer">
                                                    <span class="custom-control-label"> Buyer </span>
                                                </label>
                                                <label class="custom-control custom-radio custom-control-inline">
                                                    <input class="custom-control-input" checked="" type="radio" name="account_type" value="Seller">
                                                    <span class="custom-control-label"> Seller </span>
                                                </label>
                                                <label class="custom-control custom-radio custom-control-inline">
                                                    <input class="custom-control-input" checked="" type="radio" name="account_type" value="Both">
                                                    <span class="custom-control-label"> Both </span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group form-row">
                                            <label class="col-md-3 col-form-label">Full Name</label>
                                            <div class="col">
                                                {{ signup_form.first_name | as_crispy_field }}
                                            </div>
                                            <div class="col">
                                                {{ signup_form.last_name | as_crispy_field }}
                                            </div>
                                        </div>
                                        <div class="form-group form-row">
                                            <div class="col-md-3 col-form-label">Email</div>
                                            <div class="col-sm-9">
                                                {{ signup_form.userEmail | as_crispy_field }}
                                            </div>
                                        </div>
                                        <div class="form-group form-row">
                                            <div class="col-md-3 col-form-label">Phone</div>
                                            <div class="col-sm-9">
                                                {{ signup_form.userPhone | as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="form-group form-row">
                                            <label class="col-md-3 col-form-label">Password</label>
                                            <div class="col-sm-6">
                                                {{ signup_form.password1 | as_crispy_field }}
                                                {{ signup_form.password2 | as_crispy_field }}
                                            </div>
                                        </div>
                                        <div class="form-group form-row">
                                            <div class="col-sm-9 offset-sm-3">
                                                <label class="custom-control custom-checkbox">
                                                  <input type="checkbox" class="custom-control-input" id="customCheck1" required>
                                                  <div class="custom-control-label" for="customCheck1">I agree with <a href="#" target="_blank">terms and conditions</a></div>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-row mb-2">
                                            <div class="col-sm-9 offset-sm-3">
                                                <button type="submit" value="Sign Up" class="btn btn-primary">Sign Up</button>
                                            </div>
                                        </div>
                                    </form>

                                </div>
                        </article>

                    <article class="list-group-item">
                        <header class="filter-header">
                            <a href="" data-toggle="collapse"  data-target="#collapse2" aria-expanded="false" class="collapsed">
                                <i class="icon-control fa fa-chevron-down"></i>
                                <h3 class="title">Sign In</h3>
                            </a>
                        </header>
                        <div class="filter-content collapse {% if requires_signin %}show{% endif %}" data-parent="#collapselist" id="collapse2">
                                <form class="block-register" method="POST" action="{% url 'register:signinPage' %}">
                                    {% csrf_token %}
                                    <div class="form-group form-row">
                                            <div class="col-md-3 col-form-label">Email</div>
                                            <div class="col-sm-9">
                                                <input type="email" name="userEmail" value="" class="form-control" placeholder="johndoe@gmail.com"/>
                                            </div>
                                        </div>
                                    <div class="form-group form-row">
                                    <div class="col-md-3 col-form-label">Password</div>
                                    <div class="col-sm-9">
                                        <input type="password" name="password" value="" class="form-control" placeholder="****"/>
                                    </div>
                                </div>
                                    <div class="form-group form-row"></div>
                                    <div class="form-group form-row">
                                        <div class="col-sm-9 offset-sm-3">
                                            <label class="custom-control custom-checkbox">
                                              <input type="checkbox" class="custom-control-input" id="customCheck2">
                                              <div class="custom-control-label" for="customCheck1">Remember</div>
                                            </label>
                                        </div>
                                     </div>
                                    <div class="form-row mb-2">
                                        <div class="col-sm-9 offset-sm-3">
                                            <button type="submit" value="Sign In" class="btn btn-primary">Login</button>
                                        </div>
                                    </div>
                                </form>
                        </div>
                    </article>
                </article>
            </div>
        </div>

        <aside class="col-md-4 text-center loginlogo">
            <img src="{% static 'images/default-monochrome-white.svg' %}">
        </aside>
    </div>
{% endblock %}

register/templates/register/loginmain.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shopiva.in</title>
    <link rel="icon" href="{% static 'images/logo.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/ui.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/loginmain.css' %}">
    {% load compress %}
    {% compress css %}

    {% endcompress %}
    <script type="text/javascript">
        let user = '{{ request.user }}'
        function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>

</head>

<body>
    {% block content %}

    {% endblock %}
</body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</html>