Shopiva/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    re_path('^api/', include(('serverapi.urls', 'serverapi'), namespace='api')),
    re_path(r'^gp/', include(('order.urls', 'order'), namespace='order')),
    path('register/', include(('register.urls', 'register'), namespace='register')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

home/urls.py
# home\urls.py
from django.urls import path, re_path
from home import views

app_name = "home"
urlpatterns = [
    path('', views.home_view, name='productsPage'),
    re_path('^products/', views.product_details_view, name='productDetailsPage'),
re_path('^wishlist/', views.wishlist_view, name='wishlistPage'),
]

order/urls.py
# order\urls.py
from django.urls import path, re_path
from . import views

app_name = "order"
urlpatterns = [
    re_path(r'^profile/$', views.profile_view, name='profilePage'),
    re_path(r'^cart/$', views.cart_view, name='cartPage'),
    re_path(r'^cartToOrderRedirect/$', views.convert_cart_to_order, name='cartToOrderRedirect'),
    re_path('^orderhistory/', views.order_history_view, name='orderHistoryPage'),
    re_path('^yourtransactions/', views.transactions_view, name='transactionsPage'),
    re_path('^yourprofile/', views.profile_view, name='profilePage'),
]

register/urls.py
# register\urls.py
from django.urls import path, re_path
from register import views

app_name = "register"
urlpatterns = [
    path('', views.signup_view, name='loginPage'),
    path('signin/', views.signin_view, name='signinPage'),
    path('logout/', views.logout_view, name='logoutPage'),
]


order/models.py
# order\models.py
from hashlib import sha1
from django.db import models
from django.db.models import Sum, F
import uuid
# from home.models import Products, Customers


class Orders(models.Model):
    STATUS = (
        ('In Cart', 'In Cart'),
        ('Order placed', 'Order placed'),
        ('Shipped', 'Shipped'),
        ('Out for Delivery', 'Out for Delivery'),
        ('Delivered', 'Delivered'),
        ('Issues', 'Issues'),
        ('Cancelled', 'Cancelled'),
    )
    orderID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    customer = models.ForeignKey('home.Customers', on_delete=models.CASCADE, blank=True, null=True)
    status = models.CharField(max_length=32, choices=STATUS)
    timeStamp = models.DateTimeField(auto_now_add=True)
    transactionID = models.UUIDField(max_length=200, default=None, null=True, blank=True)

    @property
    def get_order_total(self):
        # Grand sum of price of items in Order
        # REMINDER : THIS SHOULD ONLY BE CALLED ONCE THE ORDER IS DELIVERED
        # TRANSACTION IS MADE !!!
        orderItems = self.orderitem_set.all()
        total = sum([item.get_saved_orderItem_total for item in orderItems])
        return total

    @property
    def get_cart_total(self):
        # Grand sum of price of items in cart
        if self.status == 'In Cart':
            orderItems = self.orderitem_set.all()
            total = sum([item.get_total for item in orderItems])
            return total
        else:
            return 0

    @property
    def get_cartitems_quantity(self):
        # Total no of items in cart
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    def __str__(self):
        return 'OrderID: {} | Customer: {} '.format(str(self.orderID), str(self.customer))

    class Meta:
        verbose_name_plural = "Orders"


class OrderItem(models.Model):
    """
        This is a holder for the item in the cart/order.
    """
    order = models.ForeignKey(Orders, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey('home.Products', on_delete=models.CASCADE, null=True)
    savedProductPrice = models.IntegerField(null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    timeStamp = models.DateTimeField(auto_now_add=True)

    @property
    def get_saved_orderItem_total(self):
        # return Total price of orderItem once the order's Transaction is done
        if self.savedProductPrice:
            return self.savedProductPrice * self.quantity
        else:
            return 0

    @property
    def get_total(self):
        return self.product.productPrice * self.quantity

    def __str__(self):
        return 'Product:{} | Quantity: {}'.format(self.product, self.quantity)


class ShippingAddress(models.Model):
    customer = models.ForeignKey('home.Customers', on_delete=models.SET_NULL, null=True)
    order = models.OneToOneField(Orders, primary_key=True, default=uuid.uuid4(), on_delete=models.CASCADE)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    timeStamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.address)





order/forms.py
from django.forms import ModelForm
from .models import Orders


class OrderForm():
    class Meta:
        model = Orders

order/views.py
from django.db.models import F, Subquery, OuterRef
from django.shortcuts import render, redirect

from order.models import *
from home.models import *


def cart_view(request):
    """
        cart: cart with status = 'In Cart'
        items: items in cart
    """
    if request.user.is_authenticated:
        customer = request.user
        cart, created = Orders.objects.get_or_create(customer=customer, status='In Cart')
        items = cart.orderitem_set.all()
        wishlist, created = Wishlist.objects.get_or_create(customer=customer)
    else:
        items = []
        cart = {'get_cartitems_quantity': 0, 'get_cart_total': 0}
        wishlist = {'get_wishlist_quantity': 0}
    context = {'items': items, 'wishlist': wishlist, 'cart': cart}
    return render(request, 'order/cart.html', context)


def profile_view(request):
    if request.user.is_authenticated:
        customer = request.user
        cart, created = Orders.objects.get_or_create(customer=customer, status='In Cart')
        wishlist, created = Wishlist.objects.get_or_create(customer=customer)
    else:
        cart = {'get_cartitems_quantity': 0, 'get_cart_total': 0}
        wishlist = {'get_wishlist_quantity': 0}
    context = {'cart': cart,'wishlist':wishlist}
    return render(request, 'order/profilebase.html', context)


def convert_cart_to_order(request):
    # TODO: REUSE CODE BY USING FUNCTION
    if request.user.is_authenticated:
        customer = request.user
        try:
            # find the cart
            cart = Orders.objects.get(customer=customer, status='In Cart')
            cart.status = 'Delivered'

            # TODO: BULK SAVE THE PRODUCT PRICE FOR ALL CART ITEMS
            cart.orderitem_set.all().update(savedProductPrice = F(''))
            # for cartItem in cart.orderitem_set.all().iterator():
            #     cartItem.savedProductPrice = cartItem.product.productPrice
            #     # cartItem.save(commit= False)
            cart.transactionID = uuid.uuid4()
            cart.save()
        except Orders.DoesNotExist:
            return redirect('home:productsPage')
    else:
        return redirect('home:productsPage')
    return redirect('order:orderHistoryPage')


def order_history_view(request):
    if request.user.is_authenticated:
        '''
            cart:   To show on navbar. order.get_item_quantity
            orders: To show in order history side content
            items:  Items per order
            order_and_items: zipped order and items
        '''
        customer = request.user
        wishlist, created = Wishlist.objects.get_or_create(customer=customer)

        try:
            # First try for any order history
            orders = Orders.objects.filter(customer=customer, status='Delivered').order_by('-timeStamp')
        except Orders.DoesNotExist:
            # No orders Yet
            orders = []

        try:
            # Then try for items in cart
            cart = Orders.objects.get(customer=customer, status='In Cart')
        except Orders.DoesNotExist:
            # No items in cart
            cart = {'get_cartitems_quantity': 0, 'get_cart_total': 0}

        # print('-----------\nORDERS: ', orders)
        # print('Items: ', items)
        # print('CART: ', cart)

        context = {'cart': cart,'wishlist':wishlist, 'orders': orders}
        return render(request, 'order/orderhistory.html', context)
    else:
        # If user is Anonymous
        orders = []
        cart = {'get_cartitems_quantity': 0, 'get_cart_total': 0}
        wishlist = {'get_wishlist_quantity': 0}
        context = {'cart': cart,'wishlist': wishlist, 'orders': orders}
        return render(request, 'order/orderhistory.html', context)


def transactions_view(request):
    if request.user.is_authenticated:
        customer = request.user
        wishlist, created = Wishlist.objects.get_or_create(customer=customer)
        try:
            # First try for any order history
            orders = Orders.objects.filter(customer=customer, status='Delivered').order_by('-timeStamp')
        except Orders.DoesNotExist:
            # No orders Yet
            orders = []

        try:
            # Then try for items in cart
            cart = Orders.objects.get(customer=customer, status='In Cart')
        except Orders.DoesNotExist:
            # No items in cart
            cart = {'get_cartitems_quantity': 0, 'get_cart_total': 0}

        # print('-----------\nORDERS: ', orders)
        # print('Items: ', items)
        # print('CART: ', cart)

        context = {'cart': cart,'wishlist':wishlist, 'orders': orders}
        return render(request, 'order/transctions.html', context)
    else:
        # If user is Anonymous
        orders = []
        cart = {'get_cartitems_quantity': 0, 'get_cart_total': 0}
        wishlist = {'get_wishlist_quantity': 0}
        context = {'cart': cart, 'wishlist': wishlist, 'orders': orders}
    return render(request, 'order/transctions.html', context)

order/templates/order/cart.html
{% extends 'order/cartmain.html' %}
{% load humanize %}
{% block content %}
    <section class="section-content padding-y bg" style="background-color: #f8f9fa; margin-top: 65px">
        <div class="container">

                <div class="row" >
                    <main class="col-md-8 mb-5 border"  style="border-radius: 4px;background-color: white">
                    <h4 class="card-title mt-3">Review cart</h4>
                        {% for item in items %}
                            <div class="col card-body border-bottom" id="{{ item.product.productID }}">
                                <div class="row">
                                    <div class="col-md-7">
                                        <figure class="itemside">
                                            <div class="aside">
                                                <img src="{{ item.product.productImage.url }}" class="border img-sm">
                                            </div>
                                            <figcaption class="info">
                                                <a href="{% url 'home:productDetailsPage' %}?product_id={{ item.product.productID  }}" class="title">{{ item.product.productName }}</a>
                                                <strong class>&#x20B9;{{ item.get_total | intcomma}}</strong>
                                                <div>
                                                    <a href="#" class="btn-link mr-2">Save for later</a>
                                                    <a href="#" class="btn-link text-danger update-cart" data-product="{{ item.product.productID }}" data-action="delete">Delete</a>
                                                </div>
                                            </figcaption>
                                        </figure>
                                    </div>
                                    <div class="col-md-5 text-md-right text-right">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-light update-cart" type="button" id="button-plus" data-product="{{ item.product.productID }}" data-action="remove">
                                                    <i class="fa fa-minus"></i>
                                                </button>
                                            </div>
                                            <input type="text" class="form-control" data-product="{{ item.product.productID }}" value="{{ item.quantity }}">
                                            <div class="input-group-append">
                                                <button class="btn btn-light update-cart" type="button" id="button-minus" data-product="{{ item.product.productID }}" data-action="add">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    <article class="card-body border-top">
                        <dl class="row">
                            <dt class="col-sm-10">
                                Subtotal: <span class="float-right text-muted">{{ cart.get_cartitems_quantity }} items</span>
                            </dt>
                            <dd class="col-sm-2 text-right"><strong>&#x20B9;{{ cart.get_cart_total | intcomma}}</strong></dd>
                            <dt class="col-sm-10">
                                Discount: <span class="float-right text-muted">0% offer</span>
                            </dt>
                            <dd class="col-sm-2 text-right text-danger"><strong>&#x20B9;00</strong></dd>
                            <dt class="col-sm-10">
                                Delivery Charge: <span class="float-right text-muted">Express delivery</span>
                            </dt>
                            <dd class="col-sm-2 text-right"><strong>&#x20B9;0</strong></dd>
                            <dt class="col-sm-10">Total:</dt>
                            <dd class="col-sm-2 text-right"><strong class="h5 text-dark">&#x20B9;{{ cart.get_cart_total | intcomma }}</strong></dd>
                        </dl>
                    </article>
                  </main>
                    <aside class="col-md-4">
                        <div class="card pr-0 pl-0">
                            <div class="card-body shadow">
                            <h4 class="mb-3">Overview</h4>
                            <dl class="dlist-align">
                                <dt class="text-muted">Delivery:</dt>
                                <dd>Pick-up</dd>
                            </dl>
                            <dl class="dlist-align">
                                <dt class="text-muted">Delivery type:</dt>
                                <dd>Standard</dd>
                            </dl>
                            <dl class="dlist-align">
                                <dt class="text-muted">Payment method:</dt>
                                <dd>Cash</dd>
                            </dl>
                            <hr>
                            <dl class="dlist-align">
                                <dt class="text-muted">Total</dt>
                                <dd class="h5">&#x20B9;{{ cart.get_cart_total | intcomma}}</dd>
                            </dl>
                            <hr>
                            <p class="small mb-3 text-muted">By clicking you are agree with terms of condition </p>
                            <a href="{% url 'order:cartToOrderRedirect' %}"><button class="btn btn-block {% if request.user.is_authenticated %}btn-primary{% endif %}" {% if not request.user.is_authenticated or not cart.get_cartitems_quantity %}disabled{% endif %}>Checkout</button></a>
                        </div>
                        </div>
                        <div class="card card-body mt-4">
                            <form>
                                <div class="form-group">
                                    <label>Have coupon?</label>
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Coupon code">
                                        <span class="input-group-append">
                                            <button class="btn {% if request.user.is_authenticated %}btn-primary{% endif %}" {% if not request.user.is_authenticated or not cart.get_cartitems_quantity %}disabled{% endif %}>Apply</button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </aside>
                </div>

        </div>
    </section>
{% endblock %}

order/templates/order/checkout.html
{% extends 'order/cartmain.html' %}

<h1>checkout page</h1>

order/templates/order/navbar.html
{% load static %}
<header class="main-header " id="navbar">
    <div class="container">
      <nav class="navbar navbar-expand-lg main-nav px-0">
        <a class="navbar-brand" href="{% url 'home:productsPage' %}">
            <img src="{% static 'images/logo.png' %}" alt="Shopiva">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar icon-bar-1"></span>
                        <span class="icon-bar icon-bar-2"></span>
                        <span class="icon-bar icon-bar-3"></span>
                    </button>
        <div class="collapse navbar-collapse" id="mainMenu">
          <ul class="navbar-nav ml-auto text-uppercase f1">
            <li>
              <a href="{% url 'home:productsPage' %}" class="active active-first">home</a>
            </li>
            <li>
              <a href="#about" class="text-nowrap">about us</a>
            </li>
            <li>
              <a href="#service">services</a>
            </li>
            <li>
              <a href="{% url 'home:wishlistPage' %}" id="wishlist" class="text-nowrap">Wishlist
                  {% if wishlist.get_wishlist_quantity %}
                      <span class="badge badge-danger" style="vertical-align: top;"><h7>{{ wishlist.get_wishlist_quantity }}</h7></span>
                  {% endif %}
              </a>
            </li>
            <li>
              <a href="{% url "order:cartPage" %}" id="cart" class="text-nowrap">Cart
                  {% if cart.get_cartitems_quantity %}<span class="badge badge-danger" style="vertical-align: top"><h7>{{ cart.get_cartitems_quantity }} </h7></span>{% endif %}</a>
            </li>
            <li>
              {% if request.user.is_authenticated %}<a href='{% url 'order:profilePage' %}' class="text-nowrap">Welcome {{ request.user.first_name }}</a>{% else %}<a href="{% url 'register:loginPage' %}">Login/SignUp</a>{% endif %}
            </li>
          </ul>
        </div>
      </nav>
    </div>
</header>

order/templates/order/orderhistory.html
{% extends 'order/profilebase.html' %}
{% load humanize %}
{% load static %}
{% block sidebar %}
    <a class="list-group-item" href="{% url 'order:profilePage' %}"> Your Profile </a>
    <a class="list-group-item active" href="{% url 'order:orderHistoryPage' %}"> My order history </a>
    <a class="list-group-item" href="{% url 'order:transactionsPage' %}"> Transactions </a>
    <a class="list-group-item" href="#"> Return and refunds </a>
    <a class="list-group-item" href="#">Settings </a>
    <a class="list-group-item" href="#"> My Selling Items </a>
    <a class="list-group-item" href="#"> Received orders </a>
{% endblock sidebar %}
{% block sidecontent %}
    {% if not orders %}
    <article class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="text-muted">You haven't purchased anything yet...</h3>
                </div>
            </div>
        </div>
    </article>
    {% else %}
    {% for order in orders %}
        <article class="card mb-3">
        <header class="card-header">
            <strong class="d-inline-block mr-3">Order ID: {{ order.orderID }}</strong>
            <span>Order Date: {{ order.timeStamp | naturalday:'d F Y' | capfirst}}</span>
        </header>
        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <h6 class="text-muted">Delivery to</h6>
                    <p>{{ order.customer }} <br>
                    Phone +{{ order.customer.userPhone }} Email: {{ order.customer.userEmail }} <br>
                    Location: Home number, Building name, Street 123,  Tashkent, UZB <br>
                    P.O. Box: 100123
                    </p>
                </div>
                <div class="col-md-4">
                    <h6 class="text-muted">Payment</h6>
                    <span class="text-success">
                        <i class="fab fa-lg fa-cc-visa"></i>
                        Visa  **** 4216
                    </span>
                    <p>Subtotal: &#x20B9 {{ order.get_order_total | intcomma }} <br>
                     Shipping fee:  &#x20B9 00 <br>
                     <span class="b">Total:  &#x20B9 {{ order.get_order_total | intcomma }} </span>
                    </p>
                </div>
            </div> <!-- row.// -->
        </div> <!-- card-body .// -->
        <div class="table-responsive">
        <table class="table table-hover">
            <tbody>
            {% for item in order.orderitem_set.all %}
                <tr>
                    <td width="65">
                        <img src="{{ item.product.productImage.url }}" class="img-xs border">
                    </td>
                    <td>
                        <p class="title mb-0">{{ item.product.productName }}</p>
                        <var class="price text-muted">&#x20B9 {{ item.savedProductPrice }} x {{ item.quantity }} = &#x20B9 {{ item.get_saved_orderItem_total | intcomma }}</var>
                    </td>
                    <td> Seller <br> Samsung Electronics </td>
                    <td width="250"> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="{% url 'home:productDetailsPage' %}?product_id={{ item.product.productID }}" class="btn btn-light"> Details </a> </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div> <!-- table-responsive .end// -->
    </article>
    {% endfor %}
    {% endif %}
{% endblock sidecontent %}

order/templates/order/profilebase.html
{% extends 'order/cartmain.html' %}
{% load static %}
{% block content %}
    <section class="section-content padding-y bg" style="background-color: #f8f9fa; margin-top: 65px">
        <div class="container">
            <div class="row">
                <aside class="col-md-3">
                    <!--   SIDEBAR   -->
                    <ul class="list-group">
                        {% block sidebar %}
                            <a class="list-group-item active" href="{% url 'order:profilePage' %}"> Your Profile </a>
                            <a class="list-group-item" href="{% url 'order:orderHistoryPage' %}"> My order history </a>
                            <a class="list-group-item" href="{% url 'order:transactionsPage' %}"> Transactions </a>
                            <a class="list-group-item" href="#"> Return and refunds </a>
                            <a class="list-group-item" href="#">Settings </a>
                            <a class="list-group-item" href="#"> My Selling Items </a>
                            <a class="list-group-item" href="#"> Received orders </a>
                        {% endblock sidebar %}
                    </ul>
                    <br>
                    <a class="btn btn-light btn-block" href="{% url 'register:logoutPage' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a>
                    <!--   SIDEBAR .//END   -->
                </aside>
                <main class="col-md-9">
                    {% block sidecontent %}
                        <article class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img src="{% if request.user.userImage %}{{ request.user.userImage.url }}{% else %}{% static 'images/profile.jpg' %}{% endif %}" class="img-md icon rounded-circle">
                                    </div>
                                    <div class="col-md-8">
                                        <table class="table table-borderless table-hover">
                                            <tbody>
                                            <tr>
                                                <th scope="row"><strong>Your Name</strong></th>
                                                <td>{{ request.user }}</td>
                                            </tr>
                                            <tr>
                                                <th scope="row"><strong>Your Phone Number</strong></th>
                                                <td>{%  if request.user.userPhone %}{{ request.user.userPhone}}{% else %}-{% endif %}</td>
                                            </tr>
                                            <tr>
                                                <th scope="row"><strong>Your Phone Email</strong></th>
                                                <td>{{ request.user.userEmail}}</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </article>
                    {% endblock sidecontent %}
                </main>
            </div>
        </div>
    </section>
{% endblock content %}

order/templates/order/transctions.html
{% extends 'order/profilebase.html' %}
{% load static %}
{% load humanize %}
{% block sidebar %}
    <a class="list-group-item" href="{% url 'order:profilePage' %}"> Your Profile </a>
    <a class="list-group-item" href="{% url 'order:orderHistoryPage' %}"> My order history </a>
    <a class="list-group-item active" href="{% url 'order:transactionsPage' %}"> Transactions </a>
    <a class="list-group-item" href="#"> Return and refunds </a>
    <a class="list-group-item" href="#">Settings </a>
    <a class="list-group-item" href="#"> My Selling Items </a>
    <a class="list-group-item" href="#"> Received orders </a>
{% endblock sidebar %}
{% block sidecontent %}
    {% if not orders %}
    <article class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="text-muted">No Orders means No Transactions...</h3>
                </div>
            </div>
        </div>
    </article>
    {% else %}
    {% for order in orders  %}
    <article class="card order-group mb-3">
        <header class="card-header">
            <b class="d-inline-block mr-3">Transaction ID: {{ order.transactionID }}</b>
            <span>Date: {{ order.timeStamp | naturalday:'d F Y' | capfirst }}</span>
        </header>
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <h6 class="text-muted">Payment</h6>
                    <span class="text-success">
                        <i class="fab fa-lg fa-cc-visa"></i>
                        Visa  **** 4216
                    </span>

                    <p>Subtotal: &#x20B9 {{ order.get_order_total | intcomma }} <br>
                     Shipping fee:  &#x20B9 00 <br>
                     <span class="b">Total:  &#x20B9 {{ order.get_order_total | intcomma}} </span>
                    </p>

                </div>
                <div class="col-md-4">
                    <h6 class="text-muted">Contact</h6>
                    <p>{{ order.customer }} <br> +{{ order.customer.userPhone }} <br> {{ order.customer.userEmail }}</p>
                </div>
                <div class="col-md-4">
                    <h6 class="text-muted">Shipping address</h6>
                    <p> Home 123, Building name, Street abcd,  Tashkent Uzbekistan  </p>
                </div>
            </div> <!-- row.// -->
            <hr>
            <ul class="row">
            <!-- Iterate over all items in order -->
                {% for item in order.orderitem_set.all %}
                <li class="col-md-4">
                    <figure class="itemside  mb-3">
                        <div class="aside"><img src="{{ item.product.productImage.url }}" class="img-sm border"></div>
                        <figcaption class="info align-self-center">
                            <p class="title">{{ item.product.productName }}</p>
                            <span class="text-muted text-nowrap">&#x20B9 {{ item.savedProductPrice }} x {{ item.quantity }} = &#x20B9 {{ item.get_saved_orderItem_total | intcomma }}</span>
                        </figcaption>
                    </figure>
                </li>
                {% endfor %}
            </ul>
        </div> <!-- card-body .// -->
    </article>
    {% endfor %}
    {% endif %}
{% endblock sidecontent %}